### ISSUE TITLE
Motion and contact delay

### ISSUE THREAD

**Issue by jscherry** [JoshuaMulliken/ha-wyzeapi#108]
**Is your feature request related to a problem? Please describe.**
I just switched over from using another integration where you plug the wyze hub into your vm machine etc. This integration is rock solid stable compared to the one I was using but there is a delay on the motion and contact sensors that’s quite noticeable. I have one lock, six motions, and eight contact sensors running. Is there anything I can do to cut the delay down some?

**Describe the solution you'd like**
Less delay with motion and contact sensor reporting 

**Describe alternatives you've considered**

**Additional context**

**Comment by JoshuaMulliken** [comment]
Hey @jscherry, the delay is partially caused by the reporting from the apps API. Unfortunately, this API itself is slow, and that compounds the problem that we have here.

I have set the integration to poll the service every 5 seconds, but this still does not give great results. Unfortunately, there is nothing we can do at the moment.

**Comment by jscherry** [comment]
Thanks
