### ISSUE TITLE
[Feature Request] Door Bell

### ISSUE THREAD

**Issue by whycali** [JoshuaMulliken/ha-wyzeapi#113]
**Is your feature request related to a problem? Please describe.**

No issue other than would like to view on HA
**Describe the solution you'd like**

When door bell is pushed it will show up on HA
**Describe alternatives you've considered**

**Additional context**

**Comment by JoshuaMulliken** [comment]
As far as I know, there is no way to tie into the notification system. This will require additional examination, however, so I will leave this issue open.

**Comment by shauntarves** [comment]
@whycali 

I have been working with @JoshuaMulliken to reverse-engineer a generic wyze API. I've finally cracked what they're doing in their newer requests and how they hit their own API. We now have full support for the bulbs, plugs/switches, and the new vacuum. I would love to add support for more devices, but I need someone who has these devices to be willing to work with me directly and share some access/data to I can make the code work. If you're interested in helping out, please email `shaun <at> tarves <dot> net`

**Comment by uzegonemad** [comment]
I'll be receiving a doorbell in a few days. I'm curious if it publishes button presses to the get_event_list endpoint, and if that's the case maybe we can implement something similar to #138

**Comment by JoshuaMulliken** [comment]
I have a doorbell. I can see if it does anything special.

**Comment by aeckard87** [comment]
just received a doorbell recently - happy to assist here

**Comment by JoshuaMulliken** [comment]
Don't think this is possible.

**Comment by dnestico** [comment]
I know this is closed but any updates? I have a doorbell and would love this feature as it can be used for automations..

**Comment by tggman** [comment]
I send doorbell notifications to my HA instance via Amazon Alexa using an exposed/shared input_number control. I basically set the input_number control to a unique number via an Alexa Routine. I then use that same input_control value as a trigger in a Home Assistant automation. In fact, one can use that same input_number control as a trigger for any number of tasks in HA depending on its value.
The prerequisite for this approach is a connection between your Home Assistant instance and Amazon Alexa. My connection is a perk that comes with my Home Assistant support via Nuba Casa but it can be setup independently and without Nuba Casa.

**Comment by dnestico** [comment]
@tggman  Hi sorry if this sounds dumb but can you maybe show me what this looks like? I have a nabu casa subscription and alexa is connected, so would be nice to see exactly what the automation looks like so I can try it out, thanks.

**Comment by tggman** [comment]
> @tggman Hi sorry if this sounds dumb but can you maybe show me what this looks like? I have a nabu casa subscription and alexa is connected, so would be nice to see exactly what the automation looks like so I can try it out, thanks.

Sure. No problem.

Let's call the connection between Home Assistant and Alexa the **command pipe**.  The command pipe is typically a single, exposed ```input_number``` control (although multiple ```input_boolean``` controls could also be used)
Because commands can flow both in and out of the pipe, I use the following conventions:
- A positive (+)  command pipe value = a command being SENT TO Alexa (HA is BLOWING into the pipe) 
- A negative (-) command pipe value = a command is  COMING FROM Alexa (HA is SUCKING on the pipe)
- Once the command is received and processed, the communication loop is closed when the RECEIVER RESETS the command pipe value to zero 0.

Example:
1. Someone rings my Doorbell.
2. An Alexa **routine** triggers on the button press and sets the value of the Home Assistant ```input_number.doit_alex``` control (named ```Alexa Routine Execute``` in the Alexa app) to -11.  
3. The Home Assistant automation ```Alexa HACP Received: Doorbell``` triggers when it sees ```input_number.doit_alex``` change to -11, turns on the front lights, and closes the communication loop by resetting the command pipe ```input_number.doit_alex``` back to zero

### Alexa App Side:
Here the Home Assistant control ```input_number.doit_alex``` is given the name ```Alexa Routine Execute``` in the Alexa App

<img src="https://user-images.githubusercontent.com/28722173/158069821-ef64b1a9-92de-48ae-84ea-77c1d06e6392.jpg" width=20% height=20%> 

and here is the Alexa Routine that's triggered when the doorbell rings which sets ```Alexa Routine Execute``` to -11
<img src="https://user-images.githubusercontent.com/28722173/158069853-e5a7906f-4d23-4098-9720-b93bdbb56d76.jpg" width=20% height=20%>



### Home Assistant Side:
Here's one of the automations that monitors the Alexa ```input_number.doit_alexa``` command pipe and in this case, triggers when it's value is -11 (doorbell ring):
```
- alias: "Alexa HACP Received: Doorbell"
  id: hacp_in_0011a
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ states('input_number.doit_alexa')|int(0) == -11 }}"
  action:
    - service: automation.trigger
      entity_id: automation.motion_detect_on_off_front_porch_light
      data:
        skip_condition: false
    - service: input_number.set_value       #-: reset Alexa's command pipe
      data:
        entity_id: input_number.doit_alexa
        value: 0.0
```
The applicable logbook entries:
<img src="https://user-images.githubusercontent.com/28722173/158070421-bda481dd-b1ab-4814-85fb-07e7d24e8904.jpg" width=20% height=20%>

**Comment by dnestico** [comment]
@tggman  Someone finally rang my doorbell and...

This works great! Thank you.

**Comment by rileytb** [comment]
> Don't think this is possible.

Does this mean no integrations at all with the doorbell? 
Asking less about video feed/binary sensor for button press, and more about the chime settings (their scheduling and volume) as something available in HA.
For example, after sundown set the ringer volume to 20%.

**Comment by Tweak4141** [comment]
> I send doorbell notifications to my HA instance via Amazon Alexa using an exposed/shared input_number control. I basically set the input_number control to a unique number via an Alexa Routine. I then use that same input_control value as a trigger in a Home Assistant automation. In fact, one can use that same input_number control as a trigger for any number of tasks in HA depending on its value. The prerequisite for this approach is a connection between your Home Assistant instance and Amazon Alexa. My connection is a perk that comes with my Home Assistant support via Nuba Casa but it can be setup independently and without Nuba Casa.

How would this be done independently without nabu casa?
