### ISSUE TITLE
[Feature Request] Support for motion and door/window sensors

### ISSUE THREAD

**Issue by premanandc** [JoshuaMulliken/ha-wyzeapi#320]
**Is your feature request related to a problem? Please describe.**
Wanted to check if it possible to support Wyze sense devices (motion and door/window sensors).

**Describe the solution you'd like**
Ability to use wyze sensors like all the others.
 
**Describe alternatives you've considered**
None yet

**Additional context**
N/A

**Comment by yoinx** [comment]
These were supported in the past. However, since wyze doesn't provide push endpoints all of the entities have to be polled. For binary sensors like this to be useful we have to poll them so often that we were flooding wyze's servers. Thus we were forced to drop support for them.

I would recommend perhaps trying an IFTTT integration to interact with them. Wyze developed the IFTTT applets, so they're probably using some endpoint that the apps don't.
