### ISSUE TITLE
Lock status no longer updates

### ISSUE THREAD

**Issue by tin-git** [JoshuaMulliken/ha-wyzeapi#321]
Recently, lock status no longer seem to update.
I don't see any errors in home assistant logs.

**Comment by JoshuaMulliken** [comment]
Yeah, we have a general issue with devices not updating. Have been having difficulties with the rate-limiting function and it seems like the current implementation is broken. Since this is very similar to https://github.com/JoshuaMulliken/ha-wyzeapi/issues/322 I think I will close it in favor of that one as there is more detail there.
