### ISSUE TITLE
Entities not unsubscribing from updates

### ISSUE THREAD

**Issue by brg468** [JoshuaMulliken/ha-wyzeapi#332]
**Describe the bug**
While working on https://github.com/JoshuaMulliken/ha-wyzeapi/issues/310, I ran into an issue where reloading the Wyze integration  without restarting HA seemed to produce multiple update listeners. 

 From what I can tell, the `unregister_updater` function in `base_service.py` is always passing a NoneType to `del_updater` and not removing the current update listener. Happy to help troubleshoot but I'm a bit out of my element with the update listener implementation here.

**To Reproduce**

Go to integrations
Disable an entity or device
Wait for up to 30 seconds until the next update cycle
Note the error below

**Expected behavior**

**System configuration**
System: HassIO on VM, Python 3.8 on Windows
HA Version: 2021.12.8 and  2021.9.1
WyzeApi Version: 0.1.4

**home-assistant.log**

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:526
First occurred: 12:10:22 PM (3 occurrences)
Last logged: 2:52:56 PM

Entity light.color_bulb_1 is incorrectly being triggered for updates while it is disabled. This is a bug in the wyzeapi integration
```

**Comment by yoinx** [comment]
Thanks for the report, I noticed this as well before I got tied up with a ton of stuff IRL. I planned on working on it when I get time back to work on some of the outstanding issues.

What you're saying sounds like it's on the right trail though.  I don't know what your current dev environment looks like, but I highly recommend vscode with a dev container. It makes things a lot easier to troubleshoot/track since you can actually attach a debugger to the whole thing.

Also... Just looking at it again real quick. It's a simple fix, I'm just an idiot >.<

https://github.com/JoshuaMulliken/wyzeapy/blob/ed995fb05f0814c4b83b40e7b4ffe7a418548cf2/src/wyzeapy/services/base_service.py#L47

For some reason I decided to save the updater in the base service as  x.dev_updater, but than do everything against x.updater... those need to match if it's ever going to be anything other than None

**Comment by brg468** [comment]
Ha, I did see that and messed around with it for a bit. I was so focused on trying to disable individual entities at that point that I didn't bother to see if it would work for a full reload. I'll place around with it some more.

**Comment by yoinx** [comment]
I *think* if you match those up, it should fix it completely as I don't think that HA well register the updater if the device was disabled to begin with.

I'm kinda the opposite as focus goes. I always have a bunch of branches that I jump between and things get messed up for simple things like that.

In theory, if you make all the .dev_updater properties just .updater it should resolve it.

**Comment by brg468** [comment]
Unfortunately it doesn't look like it will be that easy. It's removing the listeners now I think, but then its running into an issue with the while loop. I'll keep playing around with it.

```
File "C:\Users\brg46_000\AppData\Roaming\HATest\wyzeapy\services\update_manager.py", line 79, in update_next
    self.removed_updaters.remove(updater)
ValueError: list.remove(x): x not in list
```

**Comment by yoinx** [comment]
I think the logic there is backwards.
https://github.com/JoshuaMulliken/wyzeapy/blob/ed995fb05f0814c4b83b40e7b4ffe7a418548cf2/src/wyzeapy/services/update_manager.py#L71

The updater needs to be removed before popping the next one.

**Comment by brg468** [comment]
No worries, I’m happy to help. Might not get done real quick but I’ll keep messing around with it when I have the time.
