### ISSUE TITLE
[Feature Request] Enable access to "Sun Match" mode like the current "Music Mode"

### ISSUE THREAD

**Issue by bobloadmire** [JoshuaMulliken/ha-wyzeapi#367]
**Is your feature request related to a problem? Please describe.**
In addition to music mode, wyze also offers Sun Match effect mode, please add

**Describe the solution you'd like**
Add effect option for sun match like current music mode.

**Describe alternatives you've considered**
using the Wyze app instead of HA?

**Additional context**
No idea what to put here.

**Comment by brg468** [comment]
I think it’s doable, I’ll take a look when I get some time.

**Comment by brg468** [comment]
Any idea if Sun Match works on the white bulbs? I assume so but I only have color and light strips.

**Comment by bobloadmire** [comment]
Yes it does

**Comment by bobloadmire** [comment]
Any updates on this?

**Comment by brg468** [comment]
Yep. It was added in the PR above.

**Comment by bobloadmire** [comment]
Is it in the latest build? Not seeing the option in my strip lights

**Comment by brg468** [comment]
It’s under effects. The light has to be on to select it from the front end, or you can pass the effect in a script. 

![7DA66E22-E267-4FFA-A169-4F6270A3F1AB](https://user-images.githubusercontent.com/19143191/184540880-353d8025-3dd8-4960-a966-dd6e235d8ef2.jpeg)

**Comment by bobloadmire** [comment]
Ohhh I missed that the light has to be on. I was hoping to change the mode
even when the lights were off in a schedule

**Comment by brg468** [comment]
You can, using the light.turn_on service and passing the effect. 

https://www.home-assistant.io/integrations/light/

**Comment by bobloadmire** [comment]
Awesome, thanks!

**Comment by brg468** [comment]
@JoshuaMulliken this has been implemented, feel free to close.

**Comment by hindsight2021** [comment]
@JoshuaMulliken question related to the above.

I have 1 lightstrip + 14 bulbs (RGB) I can trigger music mode where they're all sync'd from the Wyze app, but I cannot for the life of me figure out how to trigger effect: 'music mode' for the same grouped lights (bulbs + light strip) in the wyze app as in HA.

When I group them together in HA, I see:

min_color_temp_kelvin: 1805
max_color_temp_kelvin: 6493
min_mireds: 154
max_mireds: 554
**effect_list:
  - flicker
  - leap
  - shadow
  - sun match**

But when setting the group to 'flicker' for example, only the light strip responds.

I suspect it could be a limitation, but wondering if you knew how I could trigger a music mode on all bulbs AND light strip grouped in the Wyze app, in HA as well.

**Comment by hindsight2021** [comment]
Thanks so much - I figured it had to be an API limitation some how, as essentially the lightstrip now controls the lights in a slave-master fashion I think….Looking forward to this if you ever find a route around it!Thanks again!-MB___________________________"Sent from my mobile device"On Dec 1, 2022, at 11:08 AM, Brian Rogers ***@***.***> wrote:﻿
@hindsight2021 Ill try to answer this best I can since I don't think Josh has the lightstrip. The short answer is, as of now it's not possible to control the effects of a group containing a lightstrip the way it is in the app.
I've tried to make this work as well, and regardless of how the lights are paired in the app, sending the command to the lightstrip only affects the strip, not anything else its paired with. I even tried adding the effects directly to bulbs to see if that would allow them to be used either on their own or when in a group, but it doesn't seem to be how Wyze has it set up. Groups are returned from the API during setup, but right now they are not added to HA, and even if they were, I don't know if they can be controlled the same way as individual lights.
I am sorta interesting in making this happen as well, so as I get a chance I may try messing around with it and see what if anything can be done.

**Comment by brg468** [comment]
@hindsight2021, I think I've been able to get this to work!

It turns out the bulbs can be set to music/effect mode independently of the light strip, sort of. I can send a command to the bulbs that will allow them to use the 3 effect modes when they are in a HA light group with a lightstrip. HA will not automatically add the light groups that you have in the Wyze app, but you can create a light group in HA with the same bulbs/strips and then the effect modes will work. 

This will require an update to the code to make it happen, so be on the lookout for that hopefully in the near future. Let me know if you have any questions.

**Comment by hindsight2021** [comment]
Amazing, thank you for that - that will really set my smart home goal to the next level.

Cheers mate!
