### ISSUE TITLE
Add support for door sensing and auto lock

### ISSUE THREAD

**Issue by UMB8998** [JoshuaMulliken/ha-wyzeapi#382]
Thank you for the amazing work, the project works amazing.
We are looking to be able to control the door sensing and autolock from home assistant. Can you help us integrating it?

**Comment by residencearathi** [comment]
+1

**Comment by UMB8998** [comment]
In the app it seems that you need Bluetooth to change those settings, I guess it will not work trough home assistant, but I will continue checking

**Comment by r14n** [comment]
This would be great.  I wish there was a way to trigger trash mode without manually locking and unlocking.  Or to not auto-lock when I'm in the front or backyard.

**Comment by LordNex** [comment]
He had it working for a while but I think Wyze made him stop. You can just pair it with Zigbee though and use it that way. I don't even use the Wyze app for the lock anymore. Just hit the pair button again while doing a search for Zigbee devices.

**Comment by JoshuaMulliken** [comment]
It's become difficult to continue developing support for new devices because Wyze has locked down their APIs. They've also threatened to remove all access for us because of the high load our polling puts on their servers. It's still a common issue, and their infrastructure is so brittle that it's not really feasible.

**Comment by LordNex** [comment]
Wyze as a brand has become unfeasible for use as a Home Assistant Device if you ask me. You've bent over backwards adding what support you could while they have just tied your hands every step of the way. I honestly can't believe that a few hundred of us can take down their servers, and if that is the case, they have a way larger problem. 

Honestly I've decided to move completely away from them. The only device I use anymore is the door lock and that's just because it can be controlled directly through Zigbee. Between Aqara, Amcrest, ESPHome, and ReoLink, I can easily replace their equipment with usually better hardware for about the same price. So if they don't want our money. Screw em

**Comment by LordNex** [comment]
Also, how can they lock us out specifically? How would they be able to tell that it's us vs normal use or IFTTT who they let use thier API. Sounds to me like a pay to play sort of thing really. I mean there has to be thousands of people who use Wyze with IFTTT and that isn't "Taking down their servers"?

**Comment by JoshuaMulliken** [comment]
@LordNex so there is a large number of things they can do. They can detect based on our user agent, limit the API's we use most often, etc.

They have written a custom IFTTT integration that I bet allows them to do push (much more efficient). And it also allows them to deliver information on their own timetable. If their servers are overloaded they can delay delivery.

Unfortunately I think you are right about the direction. There are way better options nowadays that I think most of us should take up.
