### ISSUE TITLE
Wyze Lock Integration Working only One way

### ISSUE THREAD

**Issue by maxcim32** [JoshuaMulliken/ha-wyzeapi#404]
The Wyze Lock integration works if you lock or unlock the lock from HA. However when you lock or unlock the lock manually or via the Wyze App then HA does not reflect the lock status change. So it looks like the integration is only working one way, that is Integration to Lock works but lock to integration does not.  The Wyze App shows any manual status change.

To Reproduce Lock/Unlock the door manually and see that the Control in the automation does not change.

Expected behavior is that the Integration control status should follow the actual lock status.

**System configuration**
Home Assistant 2022.8.4
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0
Wyze 0.1.12

**Comment by LordNex** [comment]
Been that way from the start. I ended up giving up on it and just using Zigbee to control the lock. Although you loose most Wyze control but who wants to be stuck to their "pay per use that they said they would never do" ecosystem. Although now a days there are other good options in the market that are completely local and work beautifully. 

Wyze just doesn't want to give us access and complains that we overload their servers when we do. That's why Josh had to nerf most of the best features.

**Comment by maxcim32** [comment]
Thanks for your reply. I am bit of a newbie to HA so still learning the ropes.  I have mainly Sonoff devices (over 70, including two Zigbee 3.0 Hubs) and 14 other integrations. You say that you are using Zigbee to control the lock. Can you let me know how to go about that, I might be able to use that to achieve what I want. Thanks

**Comment by snarl-123** [comment]
I find that some things just click and this is not one of them.   All I can see from the lock is its battery.   When I get some time I will take another look. 

⁣Get BlueMail for Android ​

On Aug 28, 2022, 19:23, at 19:23, maxcim32 ***@***.***> wrote:
>Thanks for your reply. I am bit of a newbie to HA so still learning the
>ropes.  I have mainly Sonoff devices (over 70, including two Zigbee 3.0
>Hubs) and 14 other integrations. You say that you are using Zigbee to
>control the lock. Can you let me know how to go about that, I might be
>able to use that to achieve what I want. Thanks
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/JoshuaMulliken/ha-wyzeapi/issues/404#issuecomment-1229626239
>You are receiving this because you are subscribed to this thread.
>
>Message ID:
***@***.***>

**Comment by kendrome** [comment]
> Been that way from the start. I ended up giving up on it and just using Zigbee to control the lock. Although you loose most Wyze control but who wants to be stuck to their "pay per use that they said they would never do" ecosystem. Although now a days there are other good options in the market that are completely local and work beautifully.
> 
> Wyze just doesn't want to give us access and complains that we overload their servers when we do. That's why Josh had to nerf most of the best features.

It wasn't that way from the start and was working just a couple months ago. I don't us the unlock feature often as this is the back door, but I've definitely used it a couple times earlier this year when doing yard work.

**Comment by JoeSchubert** [comment]
Yeah, I think this broke from a combination of me changing things earlier this year to be able to pull the battery stats (which requires a different call to Wyze's API) and Wyze at some point changing their URL parameter names. I would imagine that this has probably been causing quite a few issues with the lock ever since they changed this. PR [here](https://github.com/JoshuaMulliken/wyzeapy/pull/57)

Such a pointless change, no idea why they make these small modifications out of nowhere.

**Comment by JoeSchubert** [comment]
This has been merged in wyzeapy [here](https://github.com/JoshuaMulliken/wyzeapy/commit/147f74131c7b78686777cc77b1548c7aed518f41), so it should be fixed whenever a version update rolls out.

**Comment by LordNex** [comment]
Still never been able to get mine to work. But it seems Wyze does like nor support multi-vlan networks so again SMH

**Comment by aleck011mi** [comment]
This very much used to work the way that maxcim32 intends however Wyze did an API lockdown at one point causing Josh to have to greatly reduce the number of calls made. Home Assistant was constantly having to query the API to see lock status and only by reducing the calls were we able to keep the functionality. If you call update entity, you can force the lock status to update. What I did was put a door/window sensor on my door and every time the status of it changes, I call an update entity on the lock. This results in the desired functionality.

**Comment by JoeSchubert** [comment]
This issue is stale and was fixed in the commits I referenced back in January, rebroken in a commit added for mutexes. However, it is fixed in the latesr beta.

Therefore, this issue has become stale as a few others have since been opened with more to to date information. Closing this, if the issue persists or re-presents after 0.1.18b2 please reopen an issue.
