### ISSUE TITLE
Lock/Unlock support for Wyze Lock

### ISSUE THREAD

**Issue by patrickkamin** [JoshuaMulliken/ha-wyzeapi#92]
Hi, 
First of all, thanks for this wonderful project to support Wyze Devices.

I was wondering about the statement made in the Readme that lock/unlock isn't supported at the moment.

Is that because the Wyze API doesn't support it or is it just not yet implemented?

Thanks in advance

**Comment by JoshuaMulliken** [comment]
Hey @patrickkamin, thank you for the kind words. Unfortunately, the API cannot lock and unlock the device at least from what I have been told by my contributors.

I have heard some people have success using this project in combination with ZHA to lock and unlock the device. They use a template lock to get the status of the door from this integration and do the control from ZHA.

I wish I could do more development for that but I do not have a lock and I am renting so I cannot install one even if I got one.

**Comment by LordNex** [comment]
Would there be anything I could do or assist with to attempt to get this to function? It would seem that there should be an allowed called to the API for lock/unlock. I only say this because I'm pretty sure you can lock and unlock with Google Home once you add the Service to your home account and set the appropriate PIN. I also wonder if it couldn't be implemented in a minor way by utilizing the guest codes function. Maybe setting a specific guest code for HA and having it call that in the API? Anyway, I'd be happy to help test and work it out. I also have a Nortek ZHA/ZWave USB stick we can test with as well in case we would need to bypass the Wyze Gateway. 

On a side note, when I originally purchased the lock, the one I received was DOA as it would not enter pair mode. Does boot up and do other things though. Might pop it apart and see what's inside and if there is anything we can do from there. Either way, I'd hate to see this ability lost if it can be done. Would help me a bunch so I'm betting others as well. Thanks!

**Comment by JoshuaMulliken** [comment]
I am really not sure. I don't have one so I don't even know where to start. I can help with development but I am not highly motivated to work on this because I cannot make use of it personally. Support for this will have to come from someone who can test and develop for this.

I have heard of people using a template lock to combine the data that the API provides and use ZHA to do the actual locking and unlocking.

**Comment by LordNex** [comment]
Lately it doesn't seem like the API updates anymore for the lock. It will update its current status on a restart of HA. But doesn't seem to poll the server for any state changes anymore. 

Also, any idea on what template they were using? For a while I had my system set to sync my ZHA system with the API so that in case some one opens the lock with the keypad, app, or manually, it would also update the state of the ZHA device. But now it integration lock doesn't update it status and I haven't been able to come up with any template to reflect the change. 

I understand completely about not being motivated since you don't have one. I've got tons of IT experience but my coding abilities are still growing. Or I'd be happy to take this project over. Honestly I've seen people even mention of funding you to see if you could get something built. But again I understand. If there is any direction you could point me I'll try and figure it out myself and fork off. But again I'm just now getting into Python, Arduino, and ESPHome, but I'm pretty comfortable with HTML, ASP, PowerShell, and other things so I can probably pick it up. 

Anyway, let me know what you think. I have 5 cameras I'd like to try and figure out too. Thanks

**Comment by JoshuaMulliken** [comment]
@LordNex I think it might be somewhere in the issue history. I am not positive about what is happening with it not updating from the server. Do you know when it stopped working. Maybe a particular version number?
